### ISSUE TITLE
[Feature Proposal] Support More Visualizations

### ISSUE THREAD

**Issue by obscurecat64** [benjamin-awd/StatementSensei#21]
Hi @benjamin-awd , I tried out the app and I really like what you've created here 🔥 I would love to be able to contribute to your project if you're open to it.

I was thinking to expand the project's visualization capabilities to offer users more detailed financial insights. This will help users gain deeper insights into their spending patterns. As an initial step, I think a daily expense chart might be useful for users.

New daily expense chart:
- X-axis: dates
- Y-axis: expense amounts

Benefits:
- Provides more granular financial insights
- Help users track day-to-day spending patterns
- Will also start laying foundation for future visualization additions

Would love to know what you think, and if it aligns with your goals for the project.

I'm open to adjusting the scope or focus based on project needs 🙏

**Comment by obscurecat64** [comment]
![Screenshot 2024-10-05 at 1 46 57 PM](https://github.com/user-attachments/assets/9cbf0d7d-73cc-40af-a281-9a2e5e972d50)

![Screenshot 2024-10-05 at 1 48 49 PM](https://github.com/user-attachments/assets/35e6242c-63a8-4e4a-8992-d7c8d8246a43)

i experimented a bit with the idea of a heat map instead. What do you think?

**Comment by benjamin-awd** [comment]
Hey @obscurecat64, thanks for your feedback! 

I think that's an interesting visualization but may not be that informative for users (at least based on the limited feedback I've gotten so far)

If I added some kind of toggle to the cash flow to graph to allow users to split by day (instead of just month), would that be useful for you?
![image](https://github.com/user-attachments/assets/7831d5f5-e45a-4282-9f4f-f6e53b62c394)
